[[redirects]]
  from = "/work/*"
  status = 200
  force = true
  conditions = {Role = ["portfolioAccess"]}

[[redirects]]
 from = "/work/*"
 to = "/.netlify/functions/redirect"
 status = 200
 force = true

[functions]
  directory = "functions"